name: 🚀 Deploy workflow on PRD(AWS)

on:
  pull_request:
    branches: [dev]
      types: [closed]

# 변수 설정
env:
  PROJECT_NAME: lastdance
  AWS_REGION: ap-northeast-2
  AWS_S3_BUCKET_NAME: lastdance-github-action-s3
  AWS_CODE_DEPLOY_APP_NAME: lastdance-ec2-codedeploy
  AWS_CODE_DEPLOY_DEPLOYMENT_GROUP_NAME: lastdance-deployment-group

jobs:
  deploy:
    if: github.event.pull_request.merged == true
    environment: PRD
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      # AWS 인증 (IAM 사용자 Access Key, Secret Key 활용)
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      # 빌드 결과물을 S3 버킷에 업로드
      - name: Upload to AWS S3
        run: |
          aws deploy push \
            --application-name ${{ env.AWS_CODE_DEPLOY_APP_NAME }} \
            --ignore-hidden-files \
            --s3-location s3://$AWS_S3_BUCKET_NAME/$GITHUB_SHA.zip \
            --source .

      # S3 버킷에 있는 파일을 대상으로 CodeDeploy 실행
      - name: Deploy to AWS EC2 from S3
        run: |
          aws deploy create-deployment \
            --application-name ${{ env.AWS_CODE_DEPLOY_APP_NAME }} \
            --deployment-config-name CodeDeployDefault.AllAtOnce \
            --deployment-group-name ${{ env.AWS_CODE_DEPLOY_DEPLOYMENT_GROUP_NAME }} \
            --s3-location bucket=$AWS_S3_BUCKET_NAME,key=$GITHUB_SHA.zip,bundleType=zip
